spring:
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:mem:/meubanco
    platform: h2
    username: sa
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
      
      
server:
  port: 9191
