spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/dbprojeto1
    username: root
    password: adaumirmysql
  
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        trace: false
#       web-allow-others: true
      
      
server:
  port: 9191
